### ISSUE TITLE
Dashboard Issues

### ISSUE THREAD

**Issue by weyrougham10** [kahill2014/Hmong-Project#4]
Can't get Carousel to display properly. Console log does have some errors but some are just bootstrap

**Comment by paulknisely** [comment]
Have carousel pulling in n amount of images using PHP code. Messed around a little bit with the bootstrap classes to try and format the carousel a bit better. Doesn't look all that great though. Created a file called viewCarousel.php as to not make things confusing so that you know you are including the carousel within index.php for the dashboard mode.

Please take a look at the work, and if you think my work fixes your issue, close the issue. If not, add comments as to what else needs to be changed.
